language: python
python:
  - 3.5
services:
  - docker
install:
  - cd suite/standalone && docker-compose build
  - cd ../apache2 && docker-compose build
script:
  - cd suite/standalone && docker-compose up -d
  - cd ../apache2 && docker-compose up -d
 
